# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/garnet-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/garnet-miuicamera/common

